app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/updateapp', function()
{
    exec('composer dump-autoload');
    echo 'composer dump-autoload complete';
});


Route::get('/myapp/install/{key?}',  array('as' => 'install', function($key = null)
{
    if($key == "KR6jq0si2Pjl85xNEDR5qT3gtemxLthC"){
    try {
      echo '<br>init migrate:install...';
      Artisan::call('migrate:install');
      echo 'done migrate:install';
      
      echo '<br>init with Sentry tables migrations...';
      Artisan::call('migrate', array(
        '--package'=>'cartalyst/sentry',
        '--force' => true
        ));
      echo 'done with Sentry';
      echo '<br>init with app tables migrations...';
      Artisan::call('migrate', array(
        '--path'     => "app/database/migrations",
        '--force' => true
        ));
      echo '<br>done with app tables migrations';
      echo '<br>init with Sentry tables seader...';
      Artisan::call('db:seed', array(
        '--force' => true
        ));
      echo '<br>done with Sentry tables seader';
    } catch (Exception $e) {
      Log::info($e->getMessage());
      Response::make($e->getMessage(), 500);
    }
  }else{
    App::abort(404);
  }
}
));


Route::get('/', 'HomeController@showMain');


Route::get('/login', 'AuthController@showLogin');

Route::post('/login', 'AuthController@doLogin');

Route::get('/logout', 'AuthController@doLogout');

Route::get('/register', 'AuthController@showRegister');

Route::post('/register', 'AuthController@doRegister');


Route::get('/agent/login', 'AuthController@showAgentLogin');

Route::post('/agent/login', 'AuthController@doLogin');

Route::get('/agent/register', 'AuthController@showAgentRegister');

Route::post('/agent/register', 'AuthController@doAgentRegister');


Route::post('/agent/remove/{id}', 'ReserveController@doRemove');

Route::resource('/home', 'HomeController');

Route::resource('profile', 'ProfileController');


Route::post('profile/updateProfile/{id}', 'ProfileController@updateProfile');

Route::get('/profile/message/{id}', 'ProfileController@showMessage');

Route::post('/profile/message/{id}', 'ProfileController@doMessage');

Route::post('/review/{id}', 'ReviewController@addReview');

Route::get('/review/{id}', 'ReviewController@showList');

Route::post('/deleteReview/{id}', 'ReviewController@destroy');


//product page

//Route::resource('product', 'ProductController');

Route::get('/product', ['as' => 'product.show', 'uses' => 'ProductController@showProduct']);
Route::post('/{id}', 'ProductController@addProduct');


Route::resource('messages', 'MessagesController');

Route::get('/conversations','ConversationController@showConversations');

Route::get('/conversation/{id}','ConversationController@showMessages');

Route::get('/conversation/participant/{id}','ConversationController@showParticipant');

Route::post('/conversation/message/{id}','ConversationController@doSendMessage');

// Route::get('/conversations',function(){

//    $conversations = Auth::user()->conversations;

//    dd(count($conversations));
// });


Route::group(array('prefix' => 'manage','before' => 'manage'), function () {

	/*Route::get('/category','AdminController@showProductCategoryList');
	Route::get('/category/{id}','AdminController@showProductCategory');
	Route::get('/category/{id}/edit','AdminController@editProductCategory');*/

  Route::get('/','AdminController@index');
  
	Route::resource('category', 'ProductCategoryController');

	Route::resource('user', 'UserController');

  Route::resource('bank', 'BankController');


  Route::post('/user/remove/{id}', 'UserController@destroy');

  Route::post('/bank/remove/{id}', 'BankController@destroy');

  Route::post('/category/remove/{id}', 'ProductCategoryController@destroy');

});

Route::get('/email/welcome',function(){

  return View::make("emails.welcome");
});

Route::get('/error','HomeController@showError');

Route::get('/demo',function(){

    $productCategories =  ProductCategory::orderBy('name','asc')->lists('name', 'id');

    return View::make("product.demo",compact('productCategories'));

});


//search page
Route::get('/search/product','SearchController@showProductPage');
Route::get('/search/product/main','SearchController@showMainProduct');
Route::get('/search/product/sub','SearchController@showSubProduct');
Route::get('/search/agent','SearchController@showAgentSearch');
Route::post('/search/agent', 'SearchController@doAgentSearch');


//check if user authenticate 
Route::group(array('before' => 'auth'),function(){
    

    Route::get('/application','ApplicationController@showApplication');
    Route::get('/application/document','ApplicationController@showDocuments');
    Route::get('/application/product','ApplicationController@showProducts');  
    Route::get('/application/product/recommend','ApplicationController@showRecommend');  
    Route::get('/application/submission','ApplicationController@showSubmission');  
    
    Route::get('/saved/product', ['as' => 'product.saved', 'uses' => 'ReserveController@showProductReserve']);
    Route::get('/saved/agent', 'ReserveController@showAgentReserve');
});

Route::group(array('before' => 'auth|csrf'), function () {

    Route::post('/score/calculate', 'CalculatorController@doCalculation');
    Route::post('/score/calculate/save', 'CalculatorController@doSaveCalculation');

    Route::post('/product/saved/add', 'ReserveController@doProductSave');
    Route::post('/agent/saved/add/{id}', 'ReserveController@doAgentSave');
    
    Route::post('/product/saved/remove/{id}', 'ReserveController@doProductSavedRemove');
    Route::post('/agent/saved/remove/{id}', 'ReserveController@doAgentSavedRemove');

    Route::post('/application/apply', 'ApplicationController@doApplyAgent');
    Route::post('/application/customer', 'ApplicationController@updateCustomer');
    Route::post('/application/document/upload', 'ApplicationController@doUploadDocument');
    Route::post('/application/product/add', 'ApplicationController@doAddApplicationProduct');
    Route::post('/application/product/remove', 'ApplicationController@doRemoveApplicationProduct');
    Route::post('/application/submit', 'ApplicationController@doSubmitApplication');
    
    Route::post('/profile/updatephoto', 'ProfileController@uploadProfileImg');
    Route::post('/profile/addproduct', 'ProfileController@addProduct');
    Route::post('/profile/agent/removeproduct/{id}', 'ProfileController@removeProduct');
   

});

  Route::get('/saved', 'ReserveController@showSavedList');

  Route::get('/profile/agentproducts/{id}', 'ProfileController@getProductList');


  Route::get('/test',function(){

     $application = Application::whereCode('Jvxpth6716wQ1Ry2G46gvkOUto9mn8')->first();
     dd($application->AgentAvailableProduct()->first());
      //dd(DB::getQueryLog());
  });

app/controllers/SearchController.php
<?php

class SearchController extends \BaseController {


	public function showProductPage(){

		$scope = Input::get("scope",'');
        $MainProductId = Input::get("primary",'');
        
		$SearchURL = '';
		$PageTitle = '';

		if($scope == '' || $scope == 'main'){
			$PageTitle  = 'Products';
			$SearchURL = URL::to('/search/product/main?scope=' . $scope);	
		}else{
			$PageTitle  = 'Sub Products';
			$SearchURL = URL::to('/search/product/sub?scope=' . $scope . '&primary=' . $MainProductId);
		}
		return View::make('search.product',compact('SearchURL','PageTitle','MainProductId'));
	}

	public function showMainProduct(){
		$perPage = 12;
		$filter = false;
		$q = array();

		$keyword = Input::get("keyword",''); 
		$location = Input::get("location",'');


		$productCategories = array();

		if($keyword != '') 
		{	
		 	$filter = true;
		 	if(count($productCategories) > 0)
		 		$productCategories = $productCategories->ProductCategoryKeyword($keyword);
		 	else
		 		$productCategories = ProductCategory::ProductCategoryKeyword($keyword);
			
			$q['keyword'] = $keyword;
		}

		if($filter)
		 	$productCategories = $productCategories->paginate($perPage);
		else
		{
			$productCategories = ProductCategory::paginate($perPage);		
		} 	



		$message = "Successfully.";

		return Response::json(array(
			'error' => false,
			'result' => View::make('search._mainproduct',compact('productCategories'))->render(),
			'message' => $message),200);
	}


    public function showSubProduct(){

		$perPage = 12;
		$filter = false;
		$q = array();

		$keyword = Input::get("keyword",'');

		$service = Input::get("service",'');
		
		$bank = Input::get("bank",'');
		
		$location = Input::get("location",'');
		
		$rating = Input::get('rating','');

		$MainProductId = Input::get('primary','');

		$scope = Input::get('scope','');

		$products = array();

		$q['scope'] = $scope;

		if($MainProductId != ''){

			$filter = true;

		 	if(count($products) > 0)
		 		$products = $products->SubProduct($MainProductId);
		 	else
		 		$products = Product::SubProduct($MainProductId);
			
			$q['primary'] = $MainProductId;
		}
		
		if($keyword != '')
		{	
		 	$filter = true;
		 	if(count($products) > 0)
		 		$products = $products->ProductKeyword($keyword);
		 	else
		 		$products = Product::ProductKeyword($keyword);
			
			$q['keyword'] = $keyword;
		}

		if($service != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->ServiceName($service);
		 	else
		 		$agents = Agent::ServiceName($service);
			
			$q['service'] =  $service;
		}

		if($bank != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->BankName($bank);
		 	else
		 		$agents = Agent::BankName($bank);

		 	$q['bank'] = $bank;
		}

		if($location != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->LocationName($location);
		 	else
		 		$agents = Agent::LocationName($location);
			
			$q['location'] = $location;
		}


		if($rating != '')
		{	
		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->UserRating($rating);
		 	else
		 		$agents = Agent::UserRating($rating);

		 	$q['rating'] = $rating;
		}

		if($filter)
		 	$products = $products->paginate($perPage);
		else
		{
			$products = Product::paginate($perPage);

			//dd(count($agents));
			
		} 	

		 $message = "Successfully.";

		return Response::json(array(
		'error' => false,
		'result' => View::make('search._subproduct',compact('products','MainProductId','q'))->render(),
		'message' => $message),200);
	
	}


	public function showProduct(){

		$perPage = 12;
		$filter = false;
		$q = array();

		$keyword = Input::get("keyword",'');

		$service = Input::get("service",'');
		
		$bank = Input::get("bank",'');
		
		$location = Input::get("location",'');
		
		$rating = Input::get('rating','');

		$categories = ProductCategory::all();
		
		$banks = Bank::all();

		$products = array();
		
		if($keyword != '')
		{	
		 	$filter = true;
		 	if(count($products) > 0)
		 		$products = $products->ProductKeyword($keyword);
		 	else
		 		$products = Product::ProductKeyword($keyword);
			
			$q['keyword'] = $keyword;
		}

		if($service != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->ServiceName($service);
		 	else
		 		$agents = Agent::ServiceName($service);
			
			$q['service'] =  $service;
		}

		if($bank != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->BankName($bank);
		 	else
		 		$agents = Agent::BankName($bank);

		 	$q['bank'] = $bank;
		}

		if($location != ''){

		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->LocationName($location);
		 	else
		 		$agents = Agent::LocationName($location);
			
			$q['location'] = $location;
		}


		if($rating != '')
		{	
		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->UserRating($rating);
		 	else
		 		$agents = Agent::UserRating($rating);

		 	$q['rating'] = $rating;
		}

		if($filter)
		 	$products = $products->paginate($perPage);
		else
		{
			$products = Product::paginate($perPage);

			//dd(count($agents));
			
		} 	

/*		     $queries = DB::getQueryLog();
             $last_query = end($queries);
             Log::info($last_query);
*/
		 $message = "Successfully.";

		return Response::json(array(
		'error' => false,
		'result' => View::make('search._subproduct',compact('categories','products','q'))->render(),
		'message' => $message),200);
		//return View::make('search.subproduct',compact('categories','banks','products','q'));
	}

    

	public function showAgentSearch(){

		$perPage = 12;
		$filter = false;
		$q = array();


		$MainProductId = Input::get("primary",'');

		$SubProductId = Input::get("sub",'');

		$products = ProductCategory::all();
		
		$banks = Bank::all();

		$agents = array();


		if($MainProductId != '')
		{	
		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->PrimaryProduct($MainProductId);
		 	else
		 		$agents = Agent::PrimaryProduct($MainProductId);
			
			$q['primary'] = $MainProductId;
		}


		if($SubProductId != '')
		{	
		 	$filter = true;
		 	if(count($agents) > 0)
		 		$agents = $agents->SubProduct($SubProductId);
		 	else
		 		$agents = Agent::SubProduct($SubProductId);
			
			$q['subproduct'] = $SubProductId;
		}
        
        
        if(Auth::check() && Auth::user()->isAgent()){
            
            if(count($agents) > 0)
                $agents = $agents->where('agents.id','<>', Auth::user()->agent->id);
            else
                $agents = Agent::where('agents.id','<>', Auth::user()->agent->id);
        }



		if($filter)
		 	$agents = $agents->paginate($perPage);
		else
		{
			$agents = Agent::paginate($perPage);
		} 	

/*		     $queries = DB::getQueryLog();
             $last_query = end($queries);
             Log::info($last_query);
*/
		return View::make('search.agent2',compact('products','banks','agents','MainProductId','SubProductId','q'));
	}



// 	public function showAgentSearch(){
//
// 		$perPage = 12;
// 		$filter = false;
// 		$q = array();

// 		$keyword = Input::get("keyword",'');

// 		$service = Input::get("service",'');
		
// 		$bank = Input::get("bank",'');
		
// 		$location = Input::get("location",'');
		
// 		$rating = Input::get('rating','');

// 		$products = ProductCategory::all();
		
// 		$banks = Bank::all();

// 		$agents = array();


// 		if($primary != '')
// 		{	
// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->UserKeyword($keyword);
// 		 	else
// 		 		$agents = Agent::UserKeyword($keyword);
			
// 			$q['keyword'] = $keyword;
// 		}



		
// 		if($keyword != '')
// 		{	
// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->UserKeyword($keyword);
// 		 	else
// 		 		$agents = Agent::UserKeyword($keyword);
			
// 			$q['keyword'] = $keyword;
// 		}

// 		if($service != ''){

// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->ServiceName($service);
// 		 	else
// 		 		$agents = Agent::ServiceName($service);
			
// 			$q['service'] =  $service;
// 		}

// 		if($bank != ''){

// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->BankName($bank);
// 		 	else
// 		 		$agents = Agent::BankName($bank);

// 		 	$q['bank'] = $bank;
// 		}

// 		if($location != ''){

// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->LocationName($location);
// 		 	else
// 		 		$agents = Agent::LocationName($location);
			
// 			$q['location'] = $location;
// 		}


// 		if($rating != '')
// 		{	
// 		 	$filter = true;
// 		 	if(count($agents) > 0)
// 		 		$agents = $agents->UserRating($rating);
// 		 	else
// 		 		$agents = Agent::UserRating($rating);

// 		 	$q['rating'] = $rating;
// 		}

// 		if($filter)
// 		 	$agents = $agents->paginate($perPage);
// 		else
// 		{
// 			$agents = Agent::paginate($perPage);

// 			//dd(count($agents));
			
// 		} 	

// /*		     $queries = DB::getQueryLog();
//              $last_query = end($queries);
//              Log::info($last_query);
// */
// 		return View::make('search.agent2',compact('products','banks','agents','q'));
// 	}


	public function doAgentSearch(){


		$data = Input::all();
		$status = false;
		$message = '';
		$pageNumber = Input::get('page', 1);
		$perPage = 2;

		if(Request::ajax())
	    {

	    	$agentName = Input::get('agentName');

	    	$query = "
						select 
						u.id as UserId,
						p.id as ProfileId,
						p.first_name,
						p.last_name,
						p.name as AgentName,
						p.biography,
						p.photo_url,
						p.photointernal,
						b.name as BankName,
						l.address 
						from users as u 
						inner join agents as a on u.id = a.user_id
						left join profiles as p on u.id = p.user_id
						left join banks as b on a.bank_id = b.id
						left join locations as l on l.user_id = u.id
						where 
						p.name like '$agentName%'";

			$results = DB::select(DB::raw($query));

app/views/search/_agent.blade.php
 @if($agents != null && count($agents) > 0)
      @foreach ($agents as $i => $agent)

      <div class="col-lg-12 col-mini-6 col-md-6 col-xs-12  list-profile-member  agent-list  ">
        <div class="col-lg-2 col-xs-12 col-md-10 col-md-offset-1  col-md-10 col-mini-8 col-mini-offset-1  col-lg-offset-0 mb10"> 
        <a href="{{ $agent->user->profile->getProfileUrl() }}"> 
          <img src="{{ $agent->user->profile->getAvatar() }}" class="img-responsive"></a> 
        </div>
        <div class="col-lg-5  col-sm-8 col-xs-12 col-md-10 col-md-offset-1  col-sm-offset-2 col-lg-offset-0  ">
          <h4>{{ link_to_route('profile.show', $agent->user->profile->name ,array($agent->user->profile->uid), array('class' => '')) }}</h4>
          <p>

            @foreach($lists = $agent->getPrimaryProduct() as $i => $primary)

                @if($i != count($lists)-1)
                  <a href="{{ URL::to('/search/product?scope=subproduct&primary=' . $primary->uid ) }}">{{ $primary->name }}</a>,
                @else
                  <a href="{{ URL::to('/search/product?scope=subproduct&primary=' . $primary->uid ) }}">{{ $primary->name }}</a>
                @endif

            @endforeach
           

          </p>
            @if($agent->user->location != null)
            <p>
               {{ $agent->user->location->city }}
            </p>
            @endif
        </div>
          
       @if(Auth::check() && !$agent->user->isLoginUser())
          <div class="col-lg-1 col-xs-2 col-mini-4   mt20   text-center"> 
            <span><i class="{{ $agent->hasSaved() ? "fa fa-heart" : "fa fa-heart-o" }}" 
                     data-value="{{ $agent->id }}" 
                     url =  "{{ $agent->hasSaved() ? URL::to('/agent/saved/remove/'.$agent->uid): URL::to('/agent/saved/add/'.$agent->uid) }}"
                     data-status = "{{ $agent->hasSaved() }}"
                     style="font-size:30px;" aria-hidden="true" 
                     onclick="saveAgent(this);"></i></span> 
          </div>
        @endif
        
        <div class="col-lg-2  col-xs-4 col-mini-4   col-lg-offset-0  mt25  ml15"> <span class="message-profile-btn">Message</span> </div>
          
        @if($MainProductId != '' && $SubProductId != '')
        <div class="col-lg-1  col-xs-4 col-mini-4     col-lg-offset-0 mt20   "> 
            <form action="{{ URL::to('/application/apply') }}">
                <input type="hidden" name="MainProductId" value="{{$MainProductId}}" />
                <input type="hidden" name="SubProductId" value="{{$SubProductId}}" />
                <input type="hidden" name="AgentId" value="{{ $agent->uid }}" />
                <a href="#" 
                     type="button" class="btn btn-primary btn-md  apply-profile-btn btn-apply" style="align-item:ceter;">Apply</a>
            </form>
        </div>
        @elseif($MainProductId != '' && $SubProductId == '')
          <div class="col-lg-1  col-xs-4 col-mini-4     col-lg-offset-0 mt20   "> 
            <a href="{{ URL::to('/search/product?scope=subproduct&primary='.$MainProductId) }}" 
                     type="button" class="btn btn-primary btn-md  apply-profile-btn" style="align-item:ceter;">Apply</a>
          </div>
        @endif
      </div>


        @endforeach
      @else
      No Result
      <br/>
      <a class="btn btn-info" href="{{ URL::previous() }}">Back</a>
      @endif

         <div class="row">
      <div class="col-md-6 col-md-offset-3">
         {{  $agents->appends($q)->links(); }}
      </div>
   </div>


    <script type="text/javascript">

            function saveAgent(e){

                var link = $(e);
                var url = link.attr('url');
                var status = link.data('status');

                $.post(url).done(function(data) {

                    if(!data.error){
                       link.attr('url',data.result.url);

                        if(data.result.status == 'removed'){                      
                            link.removeClass('fa-heart');
                            link.addClass('fa-heart-o');
                        }else{
                            link.removeClass('fa-heart-o');
                            link.addClass('fa-heart');
                        }
                    }
                });

            }
        

        $(document).on("click",".btn-apply",function(e){

            var button = $(this);
            var form = $(button).closest("form");
            e.preventDefault();
            $.post(form.attr('action'),$(form).serialize()).done(function(data) {    
            if(!data.error)
                window.location = data.result.redirect_url;
            });
        });
    

    </script>

app/views/search/_mainproduct.blade.php
@if($productCategories != null && count($productCategories) > 0)
  @foreach ($productCategories as $i => $product)

    <div class="col-lg-12 col-mini-6 col-md-6 col-xs-12  list-profile-member  agent-list  ">

        <div class="col-lg-2 col-xs-12 col-md-10 col-md-offset-1  col-md-10 col-mini-8 col-mini-offset-1  col-lg-offset-0 mb10">
            <img src="{{ $product->getImageUrl() }}" class="img-responsive">
        </div>
        <div class="col-lg-5  col-sm-8 col-xs-12 col-md-10 col-md-offset-1  col-sm-offset-2 col-lg-offset-0  agent-list-profile">
            
            <a href="#">
                <h4>{{ $product->name }}</h4>
            </a>
            <a href="{{ URL::to('/search/agent?primary=' . $product->uid) }}">
                 <p>Discover agents</p>
             </a>
             <a href="profile.html">
                <p>{{ $product->city }}</p>
            </a>
        </div>

        
        <div class="col-md-2 col-lg-2  col-xs-4 col-mini-4 mt20 pull-right">
             <a href="{{ URL::to('/search/product?scope=subproduct&primary='.$product->uid) }}"><button type="button" class="btn btn-primary btn-md  apply-profile-btn" style="align-item:ceter;">View More</button></a>
        </div>
    </div>

    @endforeach
  @else
        No Result
        <br/>
        <a class="btn btn-info" href="{{ URL::previous() }}">Back</a>
  @endif 

app/views/search/_subproduct.blade.php
@if($products != null && count($products) > 0)
@foreach ($products as $i => $product)
<div class="col-lg-12 col-mini-6 col-md-6 col-xs-12  list-profile-member  agent-list  ">

    <div class="col-lg-2 col-xs-12 col-md-10 col-md-offset-1  col-md-10 col-mini-8 col-mini-offset-1  col-lg-offset-0 mb10">
        <img src="{{ $product->getImageUrl() }}" width="117" height="117">
    </div>
    <div class="col-lg-5  col-sm-8 col-xs-12 col-md-10 col-md-offset-1  col-sm-offset-2 col-lg-offset-0  agent-list-profile">
        

        <a href="{{ URL::to('/product?sub='. $product->uid . '&primary=' . $MainProductId ) }}">
            <h4>{{ $product->name }}</h4>
        </a>
        <a href="{{ URL::to('search/agent?primary=' . $MainProductId . '&sub=' . $product->uid) }}">
            <p>All Finance Agents</p>
         </a>
         <a href="profile.html">
            <p>{{ $product->city }}</p>
        </a>
    </div>
    
      @if(Auth::check())
          <div class="col-lg-1 col-xs-2 col-mini-4   mt20 heart-profile   text-center"> 
            <span><i class="{{ $product->hasSaved() ? "fa fa-heart" : "fa fa-heart-o" }}" 
                     data-value="{{ $product->uid }}" 
                     url =  "{{ $product->hasSaved() ? URL::to('/product/saved/remove/'.$product->uid): URL::to('/product/saved/add?primary=' . $MainProductId .'&sub=' .$product->uid) }}"
                     data-status = "{{ $product->hasSaved() }}"
                     style="font-size:20px;" aria-hidden="true" 
                     onclick="saveProduct(this);"></i></span> 
          </div>
        @endif

    <div class="col-lg-2  col-xs-4 col-mini-4  col-lg-offset-0  mt25  ml15 agent-list-message">
        
    </div>
    <div class="col-lg-1  col-xs-4 col-mini-4  col-lg-offset-0 mt20   ">
         <a href="{{ URL::to('/product?sub='. $product->uid . '&primary=' . $MainProductId ) }}"><button type="button" class="btn btn-primary btn-md  apply-profile-btn" style="align-item:ceter;">Apply Now</button></a>
    </div>
</div>
<!--end of listt-->
@endforeach
@else
No Result
<br/>
<a class="btn btn-info" href="{{ URL::previous() }}">Back</a>
@endif

   <div class="row">
    <div class="col-md-6 col-md-offset-3">
       {{  $products->appends($q)->links(); }}
    </div>
 </div>



    <script type="text/javascript">

        function saveProduct(e){
            
            var link = $(e);
            var url = link.attr('url');
           
            $.post(url).done(function(data) {
              
                if(!data.error){
                   link.attr('url',data.result.url);
                    
                    if(data.result.status == 'removed'){                      
                        link.removeClass('fa-heart');
                        link.addClass('fa-heart-o');
                    }else{
                        link.removeClass('fa-heart-o');
                        link.addClass('fa-heart');
                    }
                }
            });
            
        }
        
        $(function(){



        });
    </script>